### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by LorenzSchueler** [LorenzSchueler/sport-log#1]
This is intended to be a general tracking issue.
The list is not complete and will be updated over time.

Server (Rust)
- [x] user, action provider, admin authentification
- [x] endpoints for user  to all own data
- [x] endpoints for admin
- [x] endpoints for action provider
- [x] endpoints for synchronization
- [ ] endpoints for shared data
- [x] endpoints for data export

Client
- [x] local store of own data
- [x] sync on startup
- [x] push changes directly or cache them if no connection available
- [x] display and edit data
- [x] display GPS tracks and routes using [Mapbox](https://pub.dev/packages/mapbox_gl)
- [x] GPS tracking
- [ ] low energy tracking for multi day tracks (in later releases)
- [x] route planning
- [ ] map download

First Class Action Provider
- [x] Wodify
    - [x] login
    - [x] wod
- [x] Sportstracker
- [x] map matching
