### ISSUE TITLE
Live GPS tracking page

### ISSUE THREAD

**Issue by OliverPortee** [LorenzSchueler/sport-log#24]
- [x] show currently tracked path
- [x] restrict movements to movements with cardio == true
- [x] show current stats
- [x] save as cardio session
