### ISSUE TITLE
Heartrate tracking

### ISSUE THREAD

**Issue by LorenzSchueler** [LorenzSchueler/sport-log#44]
- [x] add settings to connect to heart rate monitor
- [x] add option to record heart rate in tracking page
- [x] create new page to show current heart rate
